# ******************************************************************************
#  Application Properties File
#
#  Project: Collin's Portfolio Website
#  Collin Turner 2025 
#
# ******************************************************************************

spring.application.name=portfolio

# alphavantage stock info
alphavantage.api.key=TRS39E7MB3PENHHZ
